// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNW94tSFBMfxM6JmiC1ICWruNRptMZGxs',
    appId: '1:447680021825:android:191ae7b62f885a9dc24dc0',
    messagingSenderId: '447680021825',
    projectId: 'ezbus-d14f2',
    storageBucket: 'ezbus-d14f2.firebasestorage.app',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyC5FVRGL7Wo4d8cTilFecaNQbWsHVzTLqc',
  //   appId: '1:187998321614:android:f3f7fe81d148d50c28899f',
  //   messagingSenderId: '187998321614',
  //   projectId: 'ezbus-813ac',
  //   storageBucket: 'ezbus-813ac.appspot.com',
  // );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0WRmvv6GK9jEkO7OJY1i2TSEgDTKq-bw',
    appId: '1:216763369933:ios:5d4b1a404903462b009c84',
    messagingSenderId: '216763369933',
    projectId: 'ezbus-620db',
    storageBucket: 'ezbus-620db.appspot.com',
    iosClientId: '216763369933-n6bi6ukpfvfdki7hn13n3ljdhmkk7rss.apps.googleusercontent.com',
    iosBundleId: 'com.creativeapps.ezbus',
  );
}
